[package]
name = "ambassade"
version = "1.0.2"
authors = ["Jan Allersma <jan@allersma.be>"]

[dependencies]
serde_json = "1.0"
rustyline = "2.1.0"
git2 = "0.8"
ambassade-debug = "^0"
termcolor = "1.0"
